site_name: codevinci
site_url: https://thomas-lehmann-private.github.io/codevinci
repo_url: https://github.com/thomas-lehmann-private/codevinci
site_author: Thomas Lehmann
site_description: tool for visualizing code design
site_author: Thomas Lehmann


nav:
  - index.md
  - quick-start.md
  - command-line-usage.md
  - build-system.md

theme:
  name: "material"
  logo: logo.png

markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs/examples
  - pymdownx.superfences
  - toc:
      permalink: True

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
  - autolinks
